import { VoxeetConfig } from "../../types/Voxeet";
import { Attendee, Room } from "../../types/Conference";
import { JoinOptions } from "@voxeet/voxeet-web-sdk/types/models/Options";
import Conference from "@voxeet/voxeet-web-sdk/types/models/Conference";
import { Participant } from "@voxeet/voxeet-web-sdk/types/models/Participant";
export declare const initializeVoxeet: (config: VoxeetConfig, creator: Attendee, room: Room) => Promise<Conference | undefined>;
export declare const purgeVoxeet: () => Promise<void>;
export declare const createConference: (room: Room, joinInfo?: JoinOptions) => Promise<Conference>;
export declare const joinConference: (conferenceId: string, joinOptions: JoinOptions) => Promise<Conference>;
export declare const toggleMuteSelfAttendee: () => void;
export declare const muteAttendee: (participant: Participant, isMuted: boolean) => void;
